### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by franklinworm** [ZaharX97/OWReveal#26]
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "myglobals.py", line 2, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "functions.py", line 17, in <module>
ModuleNotFoundError: No module named 'scapy'

**Comment by ZaharX97** [comment]
Yes, you need to install the other modules using pip.
(scapy / requests / Pillow / mysql-connector)

**Comment by franklinworm** [comment]
Still same `Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "myglobals.py", line 2, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "functions.py", line 28, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "csgo_demoparser\DemoParser.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "csgo_demoparser\NETMSG_pb2.py", line 5, in <module>
ModuleNotFoundError: No module named 'google'`

This is when i'm to building package for app >4.2

**Comment by franklinworm** [comment]
When I'm tried to build package for app <=4.1, This error occurs `Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "myglobals.py", line 2, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "functions.py", line 28, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "csgo_demoparser\DemoParser.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "csgo_demoparser\NETMSG_pb2.py", line 5, in <module>
ModuleNotFoundError: No module named 'google'`

**Comment by ZaharX97** [comment]
My bad, I forgot about that one.
There's one more module named 'protobuf'
It should work after that

**Comment by franklinworm** [comment]
I already installed protobuff and still got that warning

**Comment by ZaharX97** [comment]
That's weird.
When I create a new python environment and dont install modules, I got the same errors.
But after installing those 5, not anymore.
I'll try again once I get home

**Comment by ZaharX97** [comment]
I can't replicate this. I made 4 new python environments and every time after installing those 5 packages the error would disappear.
The protobuf you have only has one ' f ' at the end right?

**Comment by franklinworm** [comment]
Yes, What module should I install now?

**Comment by ZaharX97** [comment]
Only those 5 (scapy / requests / Pillow / mysql-connector / protobuf)

Make sure you have all 5 in your python environment

**Comment by franklinworm** [comment]
I already install all modules that you've been mentioned, but still got errors.

**Comment by ZaharX97** [comment]
Can you open a console and type: pip freeze

And share a screenshot?

**Comment by franklinworm** [comment]
![Screenshot_17](https://user-images.githubusercontent.com/68368765/135711692-9eaaf40b-f294-4790-8ce5-492dd1d51287.png)
![Screenshot_18](https://user-images.githubusercontent.com/68368765/135711695-b17a5324-0e66-41da-817f-50e349a08107.png)
![Screenshot_19](https://user-images.githubusercontent.com/68368765/135711699-64492780-368f-437e-b0cb-5a06e53bd899.png)
![Screenshot_20](https://user-images.githubusercontent.com/68368765/135711700-ead9eb9e-562d-47aa-a8fb-266ee86443ac.png)

**Comment by ZaharX97** [comment]
I have another ideea.
Uninstall pyinstaller (pip uninstall pyinstaller).
Install pyinstaller v4.2 (pip install pyinstaller==4.2)
If this doesn't work, I'm out of ideeas. Maybe reinstall python?

**Comment by franklinworm** [comment]
![Screenshot_9](https://user-images.githubusercontent.com/68368765/136113980-c8bba7d7-26b2-42a2-8589-ea174d221b63.png)
Its working now thanks!
